services:
  site-valorium:
    image: site-valorium:latest
    container_name: site-valorium
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "39004:80"
    environment:
      ASPNETCORE_URLS: http://+:80 # Configuration pour lier l'application au port 80 dans le conteneur
      VIRTUAL_HOST: valorium-mc.fr
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: valorium-mc.fr
      LETSENCRYPT_EMAIL: admin@valorium-mc.fr

    networks:
      - nginx-proxy-network

    restart: always 

networks:
  nginx-proxy-network:
    external: true
